enum ActionType {
		CreateList,
		UpdateList,
		DeleteList,
		AttachToList,
		DetachFromList,
		MoveList,
		CreateCard,
		EditCard,
		UpdateCard,
		DeleteCard,
		MoveCard,
		ShowModal,
		HideModal,
		ShowModalForm,
		HideModalForm,
		AddUser,
		DeleteUser,
		AddBord,
		DeleteBord,
		AttachToBord,
		DetachFromBord,
		OpenBordNameEditer,
		UpdateBordName,
}
export default ActionType;
